In [1]:
#ASSIGNMENT QUESTION

In [2]:
#NUMPY ASSIGNMENT

In [3]:
#QUESTION 1

In [4]:
#WHAT IS A PYTHON LIBRARY? WHY DO WE USE PYTHON LIBRARIES?

In [ ]:
""" A python library is a collection of pre-written code that provides a set of functions and tools that you can 
    use to perform specific tasks in your python program. These libraries are creates by other developers and are
    designed to make your life easier by providing ready-made solutions to common problems.
    
    we use python libraries for several reasons. first, they save us time and effort by providing pre-built 
    functions that we use instead of writing all the code from scratch this allows us to focus on solving the
    specific problem at hand rather than reinventing the wheel.
    
    second, python ibraries often have optimized code and alogorithms that are tested and proven to work well. by
    using these libraries, we can benifit from the expertise and experience of other developers, resulting in
    more efficient and reliable code.
    
    lastly, python libraries allow us to leverage the power of a larger community. there are countless libraries
    available for various purposes, and by using them, we can tap into a vast pool of knowledge and resourses. 
    this means we can build more complex and feature-rich applications with having to start from scratch.
    
    So, in a nutshell, python libraries are like toolboxes filled with ready-to-use tools that help us solve 
    problems faster and more efficiently. they're an essential part of the python ecosystem.

In [5]:
#QUESTION 2

In [6]:
#WHAT IS THE DIFFERENCE BETWEEN NUMPTY ARRAY AND LIST?

In [ ]:
"""The main difference between a NumPy array and a list in Python is how they store and handle data.

   A list is a built-in data structure in Python that can hold elements of different data types. It's a versatile
   container that allows you to add, remove, and modify elements easily. However, lists are not optimized for
   numerical computations.

   On the other hand, a NumPy array is a powerful data structure specifically designed for numerical operations.
   It stores elements of the same data type in a contiguous block of memory, which allows for efficient
   computation. NumPy arrays also provide a wide range of mathematical functions and operations that can be 
   applied to the entire array, making it easier to perform complex calculations.

   In terms of performance, NumPy arrays are generally faster and more memory-efficient than lists when working
   with large amounts of numerical data. They also provide additional functionalities like indexing, slicing,
   and broadcasting, which can simplify your code and make it more concise.

   So, if you're working with numerical data and need to perform computations efficiently, using NumPy arrays is
   usually the way to go. But if you're dealing with a heterogeneous collection of elements or need more
   flexibility in manipulating your data, then lists might be a better choice.

In [7]:
#QUESTION 3

In [ ]:
#FIND THE SHAPE, SIZE AND DIMENTION OF THE FOLLOWING ARRAY?
[[1,2,3,4]
[5,6,7,8],
[9,10,11,12]]

In [10]:
import numpy as np
my_array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Shape:",my_array.shape)
print("Size:", my_array.size)
print("Dimension:",my_array.ndim)
print("Element at row 1, column 2:", my_array[1,2])
print("First row:",my_array[0,:])
print("Last column:",my_array[:,-1])
print("Sum of all elements:",np.sum(my_array))
print("Maximum value:",np.max(my_array))
print("Average of each column:",np.mean(my_array,axis=0))

Shape: (3, 4)
Size: 12
Dimension: 2
Element at row 1, column 2: 7
First row: [1 2 3 4]
Last column: [ 4  8 12]
Sum of all elements: 78
Maximum value: 12
Average of each column: [5. 6. 7. 8.]


In [11]:
#QUESTION 4

In [ ]:
#write python code to access the first row of the following rray?
[[1,2,3,4]
[5,6,7,8],
[9,10,11,12]]

In [1]:
array = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
first_row = array[0]
print(first_row)

[1, 2, 3, 4]


In [2]:
#QUESTION 5

In [3]:
#HOW DO YOU ACCESS THE ELEMENT AT THE THIRD ROW AND FOURTH COLUMN FROM THE GIVEN NUMPY ARRAY?
[[1,2,3,4]
[5,6,7,8],
[9,10,11,12]]

In [4]:
import numpy as np
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
element = array[2,3]
print(element)

12


In [5]:
#QUESTION 6

In [ ]:
#WRITE CODE TO EXTRACT ALL ODD-INDEXED ELEMENTS FROM THE GIVEN NUMPY ARRAY?
[[1,2,3,4]
[5,6,7,8],
[9,10,11,12]]

In [6]:
import numpy as np
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
odd_elements = array[:,1::2]
print(odd_elements)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [7]:
#QUESTION 7

In [8]:
#HOW CAN YOU GENERATE A RANDOM 3*3 MATRIX WITH VALUES BETWEEN 0 AND 1?

In [9]:
import numpy as np
random_matrix = np.random.random((3,3))
print(random_matrix)

[[0.33569436 0.28983222 0.16552696]
 [0.00385364 0.48513251 0.59368703]
 [0.6768482  0.07625696 0.29886263]]


In [10]:
#QUESTION 8

In [11]:
#DESCRIBE THE DIFFERENCE BETWEEN np.random.rand AND npp.random.randn?

In [ ]:
"""The difference between np.random.rand and np.random.randn lies in the way they generate random numbers.

- np.random.rand generates random numbers from a uniform distribution between 0 and 1. It takes the shape of the 
  desired output as arguments. For example, np.random.rand(3, 3) will generate a 3x3 matrix with random values
  between 0 and 1.

- On the other hand, np.random.randn generates random numbers from a standard normal distribution
  (mean 0, standard deviation 1). It also takes the shape of the desired output as arguments. For example,
  np.random.randn(3, 3) will generate a 3x3 matrix with random values from a standard normal distribution.

In summary, np.random.rand generates random numbers from a uniform distribution between 0 and 1, while
np.random.randn generates random numbers from a standard normal distribution.

In [12]:
#QUESTION 9

In [15]:
#WRITE CODE TO INCREASE THE DIMENSION OF THE FOLLOWING ARRAY?
[[1,2,3,4]
[5,6,7,8],
[9,10,11,12]]

In [17]:
import numpy as np
original_array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
expanded_array = np.expand_dims(original_array,axis=0)
print(expanded_array)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [18]:
#QUESTION 10

In [19]:
#HOW TO TRANSPOSE THE FOLLOWING ARRAY IN NUMPY?
[[1,2,3,4]
[5,6,7,8],
[9,10,11,12]]

In [ ]:
import numpy as np
array = np.array([[1,2,3,4],[5,6,7,8],[9,10

In [20]:
#QUESTION 11

In [ ]:
#CONSIDERE THE FOLLOWING MATRIX:
MATRIX A: [[1,2,3,4][5,6,7,8],[9,10,11,12]]
MATRIX B: [[1,2,3,4][5,6,7,8],[9,10,11,12]]     

In [35]:
import numpy as np
A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
B = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [36]:
addition_result = A+B
print(addition_result)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [39]:
multiplication_result = A*B
print(multiplication_result)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [40]:
sum_result = np.add(A,B)
print(sum_result)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [41]:
subtraction_result = np.subtract(A,B)
print(subtraction_result)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [42]:
division_result = np.divide(B,A)
print(division_result)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [37]:
#QUESTION 12

In [38]:
#WHICH FUNCTION IN NUMPY CAN BE USED TO SWAP THE BYTE ORDER OF AN ARRAY?

In [ ]:
"""To swap the byte order of an array in NumPy, you can use the byteswap() function. This function allows you to
   change the byte order of the elements in the array.

   You can use byteswap() with the desired byte order as an argument. The byte order can be specified using the 
   following options:
- 'little': Swap to little-endian byte order.
- 'big': Swap to big-endian byte order.

In [33]:
import numpy as np

original_array = np.array([1, 2, 3, 4], dtype=np.int32)
swapped_array = original_array.byteswap('big')

print(swapped_array)

[16777216 33554432 50331648 67108864]


In [24]:
#QUESTION 13

In [25]:
#WHAT IS THE SIGNIFICANCE OF THE np.linalg.inv FUNCTION?

In [ ]:
"""The np.linalg.inv() function in NumPy is used to compute the inverse of a square matrix. The inverse of a
   matrix has various applications in linear algebra and other fields.

   The significance of np.linalg.inv() lies in its ability to solve systems of linear equations and perform 
   matrix computations. By finding the inverse of a matrix, you can solve equations of the form Ax = b, where
   A is the coefficient matrix, x is the unknown variable vector, and b is the constant vector.

  It's important to note that not all matrices have an inverse. In such cases, the np.linalg.inv() function will
  raise a LinAlgError exception.

  The np.linalg.inv() function is a powerful tool for solving linear equations, performing matrix operations,
  and solving various mathematical problems. It's widely used in scientific computing and data analysis.

In [34]:
import numpy as np

A = np.array([[2, 3], [4, 5]])
A_inv = np.linalg.inv(A)

print(A_inv)

[[-2.5  1.5]
 [ 2.  -1. ]]


In [26]:
#QUESTION 14

In [27]:
#WHAT DOES THE np.reshape FUNCTION DO, AND HOW IS IT USED?

In [ ]:
"""The np.reshape() function in NumPy is used to change the shape of an array without altering its data. It
   allows you to rearrange the elements of an array into a different shape, as long as the total number of 
   elements remains the same.

   To use np.reshape(), you pass in the array you want to reshape as the first argument, and the desired shape as
   the second argument. The shape can be specified as a tuple of integers or as a single integer for a
   1-dimensional array
   
   np.reshape() is a powerful function that allows you to manipulate the shape of arrays in various ways. It can
   be particularly useful when working with multidimensional arrays or when you need to rearrange data for a 
   specific purpose.


In [30]:
import numpy as np

original_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
reshaped_array = np.reshape(original_array, (3, 4))

print(reshaped_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
#QUESTION 15

In [29]:
#WHAT IS BROADCASTING IN NUMPY?

In [ ]:
"""In NumPy, broadcasting refers to the ability of arrays with different shapes to be used in arithmetic 
   operations. When performing operations between arrays with different shapes, NumPy automatically broadcasts 
   the arrays to make the operation possible. This allows you to perform element-wise operations on arrays of
   different sizes without explicitly writing loops.

   For example, if you have a 2x2 array and you want to add a scalar value to it, broadcasting will automatically
   expand the scalar value to match the shape of the array, so that the addition can be performed element-wise.

   Broadcasting rules in NumPy are quite flexible and allow arrays with different shapes to be combined, as long
   as they are compatible. It helps simplify the code and makes working with arrays more efficient.